# frozen_string_literal: true

source "https://rubygems.org"

gem "dotenv"
gem "zeitwerk"

gem "bootsnap", "~> 1.16"

gem "pry", require: false

gem "verse-core", github: "verse-rb/verse-core", branch: "master"
gem "verse-schema"

group :test do
  gem "rack-test"
  gem "rspec", "~> 3.0"
  gem "rubocop"
  gem "simplecov"
  gem "webmock"
end
