service_name: sync
description: Sync (import/export dataset) service
em:
  adapter: redis
plugins:
  - name: http
    config:
      show_error_details: <%= ENV.fetch("LOG_SHOW_ERROR_DETAILS", "true") %>
  - name: sequel
    config:
      mode: simple
      extensions:
        - pg_json
        - pg_array
        - pg_enum
      db:
        uri: <%= ENV.fetch("DATABASE_URI") %>
  - name: redis
    config:
      url: <%= ENV.fetch("REDIS_STREAM_URL") %>
      max_connections: 10

kv_store:
  adapter: Verse::Redis::KVStore
  config:
    plugin: :redis
    key_prefix: "sync:keys"

lock:
  adapter: Verse::Redis::Lock
  config:
    plugin: redis
    key_prefix: "sync:locks"

counter:
  adapter: Verse::Redis::Counter
  config:
    plugin: redis
    key_prefix: "sync:counters"

logging:
  level: <%= ENV.fetch("LOG_LEVEL", "info") %>

idah:
  # Jobs used for processing sync
  jobs:
    concurrency: <%= ENV.fetch("IDAH_JOBS_CONCURRENCY", 1) %>
  # Define where mounted plugins are stored.
  # Plugin system is managed directly by the application,
  # except for manual mounting and dev mode.
  plugins:
    path: <%= ENV.fetch("IDAH_PLUGIN_PATH", "plugins") %>
    # Mount modules manually using their path in the modules
    # directory
    # manual: []
    # Auto reload modules when files change (only manual plugins)
    # True if the IDAH_DEV_PLUGIN env var is set to any value
    watch: <%= !!ENV["IDAH_DEV_PLUGIN"] %>

credentials:
  account: <%= ENV.fetch("IDAH_SERVICE_ACCOUNT") %>
  password: <%= ENV.fetch("IDAH_SERVICE_PASSWORD") %>
