# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}" }

gem "verse-core", github: "verse-rb/verse-core", branch: "master"
gem "verse-http", github: "verse-rb/verse-http", branch: "features/migrate-to-sinatra-4"
gem "verse-jsonapi", github: "verse-rb/verse-jsonapi", branch: "master"
gem "verse-jsonrpc", github: "verse-rb/verse-jsonrpc", branch: "master"
gem "verse-redis", github: "verse-rb/verse-redis", branch: "master"
gem "verse-schema", "~> 1.1"
gem "verse-sequel", github: "verse-rb/verse-sequel", branch: "master"

gem "pg"

gem "dotenv"
gem "zeitwerk"

gem "puma", "~> 6"

gem "pry", require: false
gem "rake"

gem "sinatra-contrib"

gem "aasm"
gem "bootsnap", "~> 1.16"

group :test do
  gem "rack-test"
  gem "rspec", "~> 3.0"
  gem "rubocop"
  gem "simplecov"
  gem "webmock"
end

gem "duckdb", "~> 1.4"
