# frozen_string_literal: true

COMMON_PATH = ENV["COMMON_PATH"] || File.expand_path("./common", __dir__)

Dir.glob("#{COMMON_PATH}/rake/**/*.rake").each(&method(:load))
Dir.glob("#{COMMON_PATH}/tasks/**/*.rake").each(&method(:load))
