services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - media
      - dataset
      - iam
    networks:
      - app-network

  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGHOST: /var/run/postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  iam:
    build:
      context: ../app/iam
      dockerfile: Dockerfile
      args:
        BUNDLE_WITHOUT: "" # Allow all groups for dev.
        APP_ENVIRONMENT: staging
    cpus: 0.5
    mem_limit: 2g
    environment:
      - DATABASE_URI=postgres://postgres:postgres@host.docker.internal:5432/idah_iam_development
      - REDIS_STREAM_URL=redis://host.docker.internal:6379/0
      - EAGER_LOAD=1
      - IDAH_SERVICE_ACCOUNT=iam@services.idah.ai
      - IDAH_SERVICE_PASSWORD=EJvTU9fFRao4iNT911Lh90z
    ports:
      - "3000"
    volumes:
      - ../app/iam:/app
      - ../app/iam/common:/app/common
      - bundler_cache:/usr/local/bundle
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    command: ./dev-entrypoint.sh puma
    stdin_open: true
    tty: true

  media:
    build:
      context: ../app/media
      dockerfile: Dockerfile
      args:
        BUNDLE_WITHOUT: "" # Allow all groups for dev.
        APP_ENVIRONMENT: staging
    cpus: 0.6
    mem_limit: 3g
    environment:
      - DATABASE_URI=postgres://postgres:postgres@host.docker.internal:5432/idah_media_development
      - REDIS_STREAM_URL=redis://host.docker.internal:6379/0
      - EAGER_LOAD=1
      - IDAH_SERVICE_ACCOUNT=media@services.idah.ai
      - IDAH_SERVICE_PASSWORD=EJvTU9fFRao4iNT911Lh90z
    ports:
      - "3000"
    volumes:
      - ../app/media:/app
      - ../app/media/common:/app/common
      - ../plugins:/app/plugins
      - frontend_build:/app/plugins/idah-video/frontend/build
      - bundler_cache:/usr/local/bundle
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    command: ./dev-entrypoint.sh puma
    stdin_open: true
    tty: true

  dataset:
    build:
      context: ../app/dataset
      dockerfile: Dockerfile
      args:
        BUNDLE_WITHOUT: "" # Allow all groups for dev.
        APP_ENVIRONMENT: staging
    cpus: 0.5
    mem_limit: 2g
    environment:
      - DATABASE_URI=postgres://postgres:postgres@host.docker.internal:5432/idah_dataset_development
      - REDIS_STREAM_URL=redis://host.docker.internal:6379/0
      - EAGER_LOAD=1
      - IDAH_SERVICE_ACCOUNT=dataset@services.idah.ai
      - IDAH_SERVICE_PASSWORD=EJvTU9fFRao4iNT911Lh90z
    ports:
      - "3000"
    volumes:
      - ../app/dataset:/app
      - ../app/dataset/common:/app/common
      - bundler_cache:/usr/local/bundle
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    networks:
      - app-network
    command: ./dev-entrypoint.sh puma
    stdin_open: true
    tty: true

  notification:
    build:
      context: ../app/notification
      dockerfile: Dockerfile
      args:
        BUNDLE_WITHOUT: "" # Allow all groups for dev.
        APP_ENVIRONMENT: staging
    cpus: 0.5
    mem_limit: 2g
    environment:
      - DATABASE_URI=postgres://postgres:postgres@host.docker.internal:5432/idah_notification_staging
      - REDIS_STREAM_URL=redis://host.docker.internal:6379/0
      - EAGER_LOAD=1
      - IDAH_SERVICE_ACCOUNT=notification@services.idah.ai
      - IDAH_SERVICE_PASSWORD=EJvTU9fFRao4iNT911Lh90z
    ports:
      - "3000"
    volumes:
      - ../app/notification:/app
      - ../app/notification/common:/app/common
      - bundler_cache:/usr/local/bundle
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    networks:
      - app-network
    command: ./dev-entrypoint.sh puma
    stdin_open: true
    tty: true

  audit:
    build:
      context: ../app/audit
      dockerfile: Dockerfile
      args:
        BUNDLE_WITHOUT: "" # Allow all groups for dev.
        APP_ENVIRONMENT: staging
    environment:
      - DATABASE_URI=postgres://postgres:postgres@host.docker.internal:5432/idah_audit_staging
      - REDIS_STREAM_URL=redis://host.docker.internal:6379/0
      - EAGER_LOAD=1
      - IDAH_SERVICE_ACCOUNT=audit@services.idah.ai
      - IDAH_SERVICE_PASSWORD=EJvTU9fFRao4iNT911Lh90z
    ports:
      - "3000"
    volumes:
      - ../app/audit:/app
      - ../app/audit/common:/app/common
      - bundler_cache:/usr/local/bundle
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    networks:
      - app-network
    command: ./dev-entrypoint.sh puma
    stdin_open: true
    tty: true

  sync:
    build:
      context: ../app/sync
      dockerfile: Dockerfile
      args:
        BUNDLE_WITHOUT: "" # Allow all groups for dev.
        APP_ENVIRONMENT: staging
    cpus: 0.5
    mem_limit: 2g
    environment:
      - DATABASE_URI=postgres://postgres:postgres@host.docker.internal:5432/idah_sync_staging
      - REDIS_STREAM_URL=redis://host.docker.internal:6379/0
      - EAGER_LOAD=1
      - IDAH_SERVICE_ACCOUNT=sync@services.idah.ai
      - IDAH_SERVICE_PASSWORD=EJvTU9fFRao4iNT911Lh90z
    ports:
      - "3000"
    volumes:
      - ../app/sync:/app
      - ../app/sync/common:/app/common
      - bundler_cache:/usr/local/bundle
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    networks:
      - app-network
    command: ./dev-entrypoint.sh puma
    stdin_open: true
    tty: true

  setting:
    build:
      context: ../app/setting
      dockerfile: Dockerfile
      args:
        BUNDLE_WITHOUT: "" # Allow all groups for dev.
        APP_ENVIRONMENT: staging
    cpus: 0.5
    mem_limit: 2g
    environment:
      - DATABASE_URI=postgres://postgres:postgres@host.docker.internal:5432/idah_setting_development
      - REDIS_STREAM_URL=redis://host.docker.internal:6379/0
      - EAGER_LOAD=1
      - IDAH_SERVICE_ACCOUNT=setting@services.idah.ai
      - IDAH_SERVICE_PASSWORD=EJvTU9fFRao4iNT911Lh90z
    ports:
      - "3000"
    volumes:
      - ../app/setting:/app
      - ../app/setting/common:/app/common
      - ../plugins:/app/plugins
      - frontend_build:/app/plugins/idah-video/frontend/build
      - bundler_cache:/usr/local/bundle
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    depends_on:
      - frontend
    command: ./dev-entrypoint.sh puma
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ../.
      dockerfile: ./staging/Dockerfile.frontend
    ports:
      - "3000"
    volumes:
      - frontend_build:/app/frontend/build
    networks:
      - app-network
    stdin_open: true
    tty: true

volumes:
  frontend_build:
  bundler_cache:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
