service_name: media
description: Media Importer and Storage Service
plugins:
  - name: http
    config:
      show_error_details: <%= ENV.fetch("LOG_SHOW_ERROR_DETAILS", "true") %>
  - name: sequel
    config:
      mode: simple
      extensions:
        - pg_json
        - pg_array
        - pg_enum
      db:
        uri: <%= ENV.fetch("DATABASE_URI") %>

logging:
  level: <%= ENV.fetch("LOG_LEVEL", "info") %>
