em:
  adapter: redis
logging:
  level: <%= ENV.fetch("LOG_LEVEL", "debug") %>
plugins:
  - name: http
    config:
      show_error_details: <%= ENV.fetch("LOG_SHOW_ERROR_DETAILS", "true") %>
  - name: sequel
    config:
      mode: simple
      extensions:
        - pg_json
        - pg_array
        - pg_enum
      db:
        uri: <%= ENV.fetch("DATABASE_URI") %>
  - name: shrine
    config:
      storages:
        - name: default
          adapter: file_system
          config:
            path: tmp/storage/test
  - name: redis
    config:
      url: <%= ENV.fetch("REDIS_STREAM_URL") %>
      max_connections: 10