service_name: iam
description: User, role, team management service

em:
  adapter: redis
plugins:
  - name: http
    config:
      show_error_details: <%= ENV.fetch("LOG_SHOW_ERROR_DETAILS", "true") %>
  - name: sequel
    config:
      mode: simple
      extensions:
        - pg_json
        - pg_array
        - pg_enum
      db:
        uri: <%= ENV.fetch("DATABASE_URI") %>
  - name: redis
    config:
      url: <%= ENV.fetch("REDIS_STREAM_URL") %>
      max_connections: 10

kv_store:
  adapter: Verse::Redis::KVStore
  config:
    plugin: :redis
    key_prefix: "iam:keys"

lock:
  adapter: Verse::Redis::Lock
  config:
    plugin: :redis
    key_prefix: "iam:locks"

counter:
  adapter: Verse::Redis::Counter
  config:
    plugin: :redis
    key_prefix: "iam:counters"

logging:
  level: <%= ENV.fetch("LOG_LEVEL", "info") %>

credentials:
  account: <%= ENV.fetch("IDAH_SERVICE_ACCOUNT") %>
  password: <%= ENV.fetch("IDAH_SERVICE_PASSWORD") %>
