FROM ruby:3.4.2-slim

ENV APP_PATH=/idah

ENV DEBIAN_FRONTEND=noninteractive
ENV BUNDLE_SILENCE_ROOT_WARNING=1

RUN apt-get update && apt-get install -y \
    # Basic build tools
    build-essential \
    pkg-config \
    # FFmpeg and its dependencies
    ffmpeg \
    # ImageMagick and its dependencies
    imagemagick \
    libmagickwand-dev \
    # pgSQL client libraries
    libpq-dev \
    # Additional useful packages
    curl \
    wget \
    git \
    # Clean up apt cache to reduce image size
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# # Build arguments
# ENV APP_ENVIRONMENT="development"
# ENV PORT=3000

# Set the working directory
RUN mkdir -p $APP_PATH
WORKDIR $APP_PATH

RUN mkdir -p /vendor/bundle
RUN bundle config set --local path /vendor/bundle
RUN bundle config set force_ruby_platform true

CMD ["irb"]
