volumes:
  generator_bundle:
  frontend_node_modules:

services:
  doc-generator:
    container_name: doc-generator
    image: doc-generator
    build:
      context: ../
      dockerfile: ./doc/Dockerfile.generator
    environment:
      - COMMON_PATH=../../common
    stdin_open: true
    tty: true
    volumes:
      - ../app:/idah/app:cached
      - ../common:/idah/common:cached
      - ../bin/all_services:/idah/bin/all_services
      - ./bin/generate_openapi:/idah/bin/generate_openapi
      - ./openapi:/openapi:cached
      - generator_bundle:/vendor/bundle
    command: >
      sh -c "
        ./bin/all_services bundle install &&
        ./bin/generate_openapi &&
        bash
      "
    extra_hosts:
      - localhost:host-gateway

  doc-swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: doc-swagger
    ports:
      - "4002:8080"
    depends_on:
      - doc-generator
    volumes:
      # Mount the local 'swagger' directory to the container's '/app' directory
      - ./openapi:/usr/share/nginx/html/openapi
    environment:
      CONFIG_URL: /openapi/swagger.json

  doc-frontend:
    container_name: doc-frontend
    image: doc-frontend
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    volumes:
      - ./public:/app:cached
      - ./openapi:/app/public/data:cached
      - frontend_node_modules:/app/node_modules
    ports:
      - "4001:4001"
    depends_on:
      - doc-generator