import type { ColumnsSettings } from "$lib/components/app/data-table/DataTable.types";

export const projectTaskColumns: ColumnsSettings = {
	name: {
		label: "Name",
		dataType: "string",
		clickable: true,
		sortable: true,
		filterable: true,
		filterOptions: {
			filterKey: "name",
			filterBy: "string",
			filterOperation: "match",
		},
		visible: true,
		hidable: false,
	},
	status: {
		label: "Status",
		dataType: "enum",
		clickable: false,
		sortable: true,
		filterable: true,
		filterOptions: {
			filterKey: "status",
			filterBy: "multiple-select",
			filterOperation: "in",
		},
		visible: true,
		hidable: false,
	},
	issue: {
		label: "Issues",
		dataType: "number",
		clickable: false,
		sortable: true,
		filterable: true,
		filterOptions: {
			filterKey: "issue",
			filterBy: "number-range",
			filterOperation: "eq",
		},
		visible: true,
		hidable: false,
	},
	label_time: {
		label: "Label Time",
		dataType: "number",
		clickable: false,
		sortable: true,
		filterable: true,
		filterOptions: {
			filterKey: "label_time",
			filterBy: "number-range",
			filterOperation: "eq",
		},
		visible: true,
		hidable: false,
	},
	review_time: {
		label: "Review Time",
		dataType: "number",
		clickable: false,
		sortable: true,
		filterable: true,
		filterOptions: {
			filterKey: "review_time",
			filterBy: "number-range",
			filterOperation: "eq",
		},
		visible: true,
		hidable: false,
	},
	created_on: {
		label: "Created on",
		dataType: "datetime",
		clickable: false,
		sortable: true,
		filterable: true,
		filterOptions: {
			filterKey: "created_on",
			filterBy: "date-range",
			filterOperation: "eq",
		},
		visible: true,
		hidable: false,
	},
	last_updated: {
		label: "Last updated",
		dataType: "datetime",
		clickable: false,
		sortable: true,
		filterable: true,
		filterOptions: {
			filterKey: "last_updated",
			filterBy: "date-range",
			filterOperation: "eq",
		},
		visible: true,
		hidable: false,
	},
	annotator: {
		label: "Annotator",
		dataType: "string",
		clickable: false,
		sortable: true,
		filterable: true,
		filterOptions: {
			filterKey: "annotator",
			filterBy: "string",
			filterOperation: "match",
		},
		visible: true,
		hidable: false,
	},
	reviewer: {
		label: "Reviewer",
		dataType: "string",
		clickable: false,
		sortable: true,
		filterable: true,
		filterOptions: {
			filterKey: "reviewer",
			filterBy: "string",
			filterOperation: "match",
		},
		visible: true,
		hidable: false,
	},
};
