service_name: setting
description: Setting and Plugins Management Service
em:
  adapter: redis
plugins:
  - name: http
    config:
      show_error_details: <%= ENV.fetch("LOG_SHOW_ERROR_DETAILS", "true") %>
  - name: sequel
    config:
      mode: simple
      extensions:
        - pg_json
        - pg_array
        - pg_enum
      db:
        uri: <%= ENV.fetch("DATABASE_URI") %>
  - name: redis
    config:
      url: <%= ENV.fetch("REDIS_STREAM_URL") %>
      max_connections: 10

kv_store:
  adapter: Verse::Redis::KVStore
  config:
    plugin: :redis
    key_prefix: "setting:keys"

lock:
  adapter: Verse::Redis::Lock
  config:
    plugin: redis
    key_prefix: "setting:locks"

counter:
  adapter: Verse::Redis::Counter
  config:
    plugin: redis
    key_prefix: "setting:counters"

logging:
  level: <%= ENV.fetch("LOG_LEVEL", "info") %>
